project_id = "agnimxxiqcbzbdxcqtzz"

[functions.paystack-initialize]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.translate-product]
verify_jwt = false

[functions.check-commission-milestone]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.check-price-alerts]
verify_jwt = false